DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS hits (
                                          hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          hit_app VARCHAR(32) NOT NULL,
                                          hit_uri VARCHAR(128) NOT NULL,
                                          hit_ip VARCHAR(16) NOT NULL,
                                          hit_time TIMESTAMP WITHOUT TIME ZONE,
                                          CONSTRAINT pk_hit PRIMARY KEY (hit_id)
);
